### ISSUE TITLE
sample.groups are not extracted automatically anymore

### ISSUE THREAD

**Issue by rrydbirk** [kharchenkolab/cacoa#13]
We should discuss whether this is desired. Originally, sample.groups were extracted automatically based on sample names and ref.level. Now, if one doesn't set sample.groups argument (#8bf3d95):

> cao <- cacoa:::Cacoa$new(con, cell.groups = annotation, ref.level="wt", n.cores=30)
Error: Must request at least one colour from a hue palette.
> traceback()
6: stop("Must request at least one colour from a hue palette.", 
       call. = FALSE)
5: (scales::hue_pal())(length(levels(sample.groups)))
4: rev((scales::hue_pal())(length(levels(sample.groups))))
3: setNames(rev((scales::hue_pal())(length(levels(sample.groups)))), 
       levels(sample.groups))
2: .subset2(public_bind_env, "initialize")(...)
1: cacoa:::Cacoa$new(con, cell.groups = annotation, ref.level = "wt", 
       n.cores = 30)

**Comment by VPetukhov** [comment]
The previous implementation implied one particular encoding of conditions in sample names. I don't see why it would be a general case, so would prefer to keep it removed.
