### ISSUE TITLE
no dependency on psych package declared

### ISSUE THREAD

**Issue by pkharchenko** [kharchenkolab/cacoa#16]
$estimateCellLoadings() requires psych package, which is not declared. Please double-check if it's needed.
edit: same thing goes for the 'coda.base' pacakage

**Comment by evanbiederstedt** [comment]
Note that if packages are only use 1-2 more functions, it's best to put them in `Suggests` in the `DESCRIPTION` file. 

If you do this, please use the following format for these functions: 

```
  if (!requireNamespace("PACKAGE_NAME", quietly = TRUE)) {
    stop("Package \"PACKAGE_NAMEt\" is needed for this function to work. Please install it with XYZ.", call. = FALSE)
  }
  ```


e.g.

https://github.com/kharchenkolab/conos/blob/master/R/integrations.R#L37-L39


CC @iganna

**Comment by VPetukhov** [comment]
> If you do this, please use the following format for these functions:

@evanbiederstedt , actually, for Cacoa I added a separate function [`checkPackageInstalled`](https://github.com/kharchenkolab/cacoa/blob/master/R/utils.R#L12) that saves space and provides much more meaningful messages (e.g. [here](https://github.com/kharchenkolab/cacoa/blob/0d9cbabf9ec3507290173c833e36eea04780ebff/R/cluster_free.R#L22) and [here](https://github.com/kharchenkolab/cacoa/blob/0d9cbabf9ec3507290173c833e36eea04780ebff/R/cell_density.R#L162)). Should we maybe move it to sccore and gradually switch to using it in other packages?

**Comment by evanbiederstedt** [comment]
> Should we maybe move it to sccore and gradually switch to using it in other packages?

That works too---either approach should work. 

> Need to add that for Cacoa I added a separate function checkPackageInstalled that saves space and provides much more meaningful messages (e.g. here and here). 

That works. We'll still need to add those packages to `Suggests` however; them's just the rules.

**Comment by VPetukhov** [comment]
Fixed in https://github.com/kharchenkolab/cacoa/commit/3a06e2aa8a085b7e832fc18be0ca1a54fee8e50f
