### ISSUE TITLE
Possible wrong contour for overlapping 

### ISSUE THREAD

**Issue by hiraksarkar** [kharchenkolab/cacoa#19]
Hi,

Thanks for developing cacoa. 

While running `estimateCellDensity` and highlighting contours of clusters 2 and 9 in the following plot, I get overlapping contours, 

code snippet
```
cao.8$estimateCellDensity()
options(repr.plot.height=12, repr.plot.width=12, res=150 ) 
p0 <- cao.8$plotEmbedding(groups=conos.8$clusters$leiden$groups, alpha=alpha, size=size, title='annotation', plot.na=F, show.legend=F)
pl <- cao.8$plotCellDensity(add.points = TRUE,contours = c(2,9),show.grid=T)
p1 <- cao.8$plotEmbedding(groups=sample_type, alpha=alpha, size=size, title='diagnosis', mark.groups=F) +
    theme(legend.position=c(0.85, 0.15)) +
    guides(color=guide_legend(override.aes = list(size=3,alpha=0.8),title=''))
cowplot::plot_grid(plotlist = c(list(p0),list(p1),pl),  nrow = 2)
```

![image](https://user-images.githubusercontent.com/9473877/143917653-3b2a18f2-c190-4cbc-98a1-0203e9ee1aed.png)

Upon a close inspection, I see the there is indeed a large overlap between 2 and 9, 

![image](https://user-images.githubusercontent.com/9473877/143917763-9bc575b4-89ff-4971-9ec4-06b600a5ff5c.png)

Even then, should not we have a larger contour for cluster 9?

**Comment by VPetukhov** [comment]
Hi Hirak,
We use [very simple code](https://github.com/kharchenkolab/cacoa/blob/1b56a2d02d4dcac05857c5a4a18c031db6ffdaad/R/cell_density.R#L87) for contours, so it's not ours implementation. To my understanding, it works well only for uni-modal distributions, and otherwise it highlights the most dense mode. Sometimes it is possible to bypass the problem by setting confidence (`contour.conf`) to a very small value like '1%'.

**Comment by hiraksarkar** [comment]
Hi Viktor, 

Thanks a lot for more insight. Great to know we were calling ` ks::kde`.

**Comment by evanbiederstedt** [comment]
I think the best approach here is for us to clarify this in the tutorial to inform the user. The user could adjust the contour lines by modifying this parameter. 

I wanted to check this out: 

> it works well only for uni-modal distributions

It looks like `contour.conf` works fair well for this. Perhaps it should be something like 5% by default...

Here's with `contour.conf="1%"`:

<img width="871" alt="Screen Shot 2021-11-29 at 8 48 37 PM" src="https://user-images.githubusercontent.com/6968193/143970923-eefb8154-aa09-42e9-bf40-6564c02dc490.png">



Source code: 

```
library(ggplot2)
library(conos)
library(cacoa)

alpha <- 0.1
size <- 0.1

tumor_cells = names(conos.8$clusters$leiden$groups)[grepl('tumor', names(conos.8$clusters$leiden$groups))]
adrenal_cells = names(conos.8$clusters$leiden$groups)[grepl('adrenal', names(conos.8$clusters$leiden$groups))] 
sample_type = c(rep('tumor',length(tumor_cells)), rep('adrenal', length(adrenal_cells)))
names(sample_type) = c(tumor_cells, adrenal_cells)
sample_type = as.factor(sample_type)

cao.8$estimateCellDensity()

p0 <- cao.8$plotEmbedding(groups=conos.8$clusters$leiden$groups, alpha=alpha, size=size, title='annotation', plot.na=F, show.legend=F)
pl <- cao.8$plotCellDensity(add.points = TRUE,contours = c(2,9),show.grid=T,  contour.conf='1%')

p1 <- cao.8$plotEmbedding(groups=sample_type, alpha=alpha, size=size, title='diagnosis', mark.groups=F) +
    theme(legend.position=c(0.85, 0.15)) +
    guides(color=guide_legend(override.aes = list(size=3,alpha=0.8),title=''))

cowplot::plot_grid(plotlist = c(list(p0),list(p1),pl),  nrow = 2)
```

**Comment by evanbiederstedt** [comment]
My recommendation is to close; feel free to overrule me.
