### ISSUE TITLE
Understanding resampling parameters for DEG analysis

### ISSUE THREAD

**Issue by Laura19993** [kharchenkolab/cacoa#24]
Hi,
I want to calculate DE genes and used the following command: 

cao$estimatePerCellTypeDE(max.cell.count=50, name='de',
                        resampling.method='bootstrap', max.resamplings=29, n.cores=50)

My cell types have quite different sizes. Ranging from less than 100 to more than 3000. Which settings to you recommend? I noticed that when I change the number of max.cell.count to 100 I get way lower p.adj and thus a higher number of significant DE genes. Moreover I am always getting these warning messages (see image). Is it fine to ignore? (Microglia is the smallest cluster with only 55 cells.) 
Should I calculate rather without resampling?
![grafik](https://user-images.githubusercontent.com/63233675/164673606-37e714fa-ab8f-4c32-8e8e-12735a67dabf.png)

Thanks for your help!

**Comment by VPetukhov** [comment]
Hi Laura,
You don't need to set `resampling.method` unless you want to analyse the number of DE genes as a metric by itself. Can you please try the simplest `cao$estimatePerCellTypeDE(n.cores=50)`?

**Comment by Laura19993** [comment]
Okay yes I tried. Now I do not get the warnings because it is not performing resampling. The number of DE genes is higher in bigger clusters (size dependency). Are we fine with size-dependency as long as we are aware of it?
I do not really understand what you mean by "unless you want to analyse the number of DE genes as a metric by itself".

**Comment by VPetukhov** [comment]
> The number of DE genes is higher in bigger clusters (size dependency). Are we fine with size-dependency as long as we are aware of it?

Size dependency matters only if we make conclusions based on the number of DE genes instead of their content. That's what i mean by 'analyse the number by itself'. For example, if you say that "Cluster A has more genes than Cluster B and that means ...", it would likely be incorrect without resampling. But if you see that for DE without resampling "Gene X is significantly changed in Cluster A" that is still a valid conclusion regardless of the cluster size.

**Comment by Laura19993** [comment]
Okay thanks makes sense now

**Comment by VPetukhov** [comment]
Resampling can be used for two goals: 
1. Fixing number of cells and samples for estimating comparable number of DE genes per cell type. In this case, 'number of DE genes per cell type' is a measure of expression shift. And exact genes are not needed. To do that, you just need to set `n.cells.subsample` and `fix.n.samples` to some reasonable number.
2. Estimating variability of DE results for exclusion of samples. That can be used either to get plots similar to [Fig. 5A-F](https://www.biorxiv.org/content/10.1101/2022.03.15.484475v1.full) here or to estimate individual gene variability scores and exclude those genes from interpretation. For that, you don't fix number or cells nor samples, setting `resampling.method='loo'` instead. It will estimate DE iteratively excluding each of the samples.

> Does it mean after each round of sampling all the cells are put back and a new sample is drawn? And how many cells are drawn each round? If we set max.cell.count = 50, are then 50 cells drawn each round?

The parameter was renamed to clarify that. It's not `max.cell.count` but `n.cells.subsample` now. So yes, if you set it to 50, it will draw 50 cells from each cell type, omitting those with not enough cells. Then they're 'put back' and a new sample is drawn. The same can be done with samples using `fix.n.samples`.
