### ISSUE TITLE
estimateDiffCellDensity() drops negative values

### ISSUE THREAD

**Issue by rrydbirk** [kharchenkolab/cacoa#26]
After calculations, plotCellDensity() shows higher densities for some cells in ref.level. However, 

`> cao$test.results$cell.density$diff$wilcox$adj %>% min`
`[1] 0`

So no negative values are included in plotDiffCellDensity().

**Comment by rrydbirk** [comment]
Furthermore,

`> cao$plotDiffCellDensity(adjust.pvalues = F)`
`Warning message:`
`"invoke()" is deprecated as of rlang 0.4.0.`
`Please use "exec()" or "inject()" instead.`

**Comment by VPetukhov** [comment]
> `cao$test.results$cell.density$diff$wilcox$adj %>% min`

You're looking at adjusted values. Some random variations in density can be set to 0 after adjustment.

**Comment by rrydbirk** [comment]
Hi Viktor. Thanks, I'm aware of this. However, looking at the densities I was surprised that no "negative" densities were plotted. But if you already considered this, it's probably how it should be.
