### ISSUE TITLE
estimateClusterFreeDE returns only NaNs and 0s (seurat object)

### ISSUE THREAD

**Issue by amissarova** [kharchenkolab/cacoa#30]
Hi!
I'm looking into cluster-free DE detection. I have a Seurat object with an added graph for joint embedding using `FindNeighbors` as suggested per the installation tutorial.  
However, as an output of `estimateClusterFreeDE` I get matrix, where z, z.adj and lfc are all either NaNs or 0s (suggesting no DE) - even for genes for which I know I should get DE signal. This is consistent with the increase of k neighbors and using either kNN or sNN graphs. 
Do you maybe have any ideas of why is this happening? I'm planning on trying conos as well but ideally would like to have it working for seurat. 

Thanks!

**Comment by amissarova** [comment]
ah and also, what is quite confusing me tbh is that i cant find the function `estimateClusterFreeDE` in R folder

**Comment by amissarova** [comment]
Also, I just checked and both fields `reference` and `target` are also NaNs  which is definitely not right.
Not sure what I am doing wrong, seurat counts and data slots are both correct and as expected.

**Comment by amissarova** [comment]
Sorry, was a bug on my end -- condition vector was labeled with cell ids instead of sample ids

**Comment by pkharchenko** [comment]
Hi Alsu. Thanks for reporting issues. We’re gearing up to improve/extend the package, so if you have suggestions, please let us know.
Best,
-peter.
