### ISSUE TITLE
cao$plotOntology() filtering by "up" and "down"dos not work

### ISSUE THREAD

**Issue by Laura19993** [kharchenkolab/cacoa#32]
The function cao$plotOntology() shows always the same result no matter which of "down", "up" or "all" I pass to genes parameter. I checked manually and I think it plots all GO terms. If it matters: I use the function on GSEA results.
Moreover, it does no work for me to plot the GSEA results as a barplot.

Best,
Laura

**Comment by rrydbirk** [comment]
Fixed in 4717965.
