### ISSUE TITLE
estimateMetadataSeparation() gave an error - "object 'n.permutations' not found"

### ISSUE THREAD

**Issue by Angel-Wei** [kharchenkolab/cacoa#47]
Dear Cacoa team,

Previously, I encountered an error of `plotOntologyHeatmapCollapsed` function and I got it resolved after installing the Cacoa in `dev` version (like mentioned in the issue I created earlier #45 .Thanks for the help!). Any other function in my pipeline was working fine. However,
when I was trying to use 

`cao$estimateMetadataSeparation(sample.meta=cao$misc$sample_metadata)`,

it gave me an error like this:
![Screenshot 2023-06-15 at 1 47 50 PM](https://github.com/kharchenkolab/cacoa/assets/39067474/597a793e-e488-4163-992b-8207bf2adf79)
 and I didn't see this in old Cacoa objects I created before I re-install the `dev` version. Though I didn't see failure of using this function affected other functions, I wonder Is there anything else I can do to fix this problem? Thank you so much for the help in this matter!

**Comment by rrydbirk** [comment]
Hi @Angel-Wei 

Can you provide `traceback()` of the error? Thanks!

**Comment by Angel-Wei** [comment]
Sure, I built this object under R 4.1.3 and cacoa 0.4.0. Here's the information of traceback(). Thanks for the reply!

![Screenshot 2023-06-21 at 10 25 36 AM](https://github.com/kharchenkolab/cacoa/assets/39067474/f9f53167-aa29-4be8-a061-1ba59f95bbf8)

**Comment by Angel-Wei** [comment]
Not sure if this info helps, it seems that I didn't get this error when building Cacoa objects under R 4.2.0 and cacoa 0.4.0.

**Comment by rrydbirk** [comment]
Hi @Angel-Wei 

The error doesn't make sense, it seems that the `n.permutations` argument is not included in your object. You can check it by doing `cao$estimateMetadataSeparation` and see if the argument is included in the function call. Sometimes, parsing old R6 objects to newer versions induces errors. Hence, sometimes it's just better to start over with object creation :-)

If you don't get the error in R 4.2.0, I think I'll close this issue. Please let me know if you keep having problems with this function.

/Rasmus

**Comment by Angel-Wei** [comment]
Hi Rasmus, thank you so much for the info. I think the default n.permutations = 5000 was passed in the argument for the function call `cao$estimateMetadataSeparation`.

  > function (sample.meta, space = "expression.shifts", dist = NULL, 
    space.name = NULL, sample.subset = NULL, name = "metadata.separation", 
    n.permutations = 5000, trim = 0.05, k = 20, show.warning = TRUE, 
    verbose = self$verbose, n.cores = self$n.cores, adjust.pvalues = TRUE, 
    p.adjust.method = "BH", pvalue.cutoff = 0.05)`

However, I found it I can use the function after I load it under R 4.2.0 and call `cao %<>% Cacoa$new()` first. Thanks for the help anyway!
