### ISSUE TITLE
plotSampleDistances with metadata gives error

### ISSUE THREAD

**Issue by Laura19993** [kharchenkolab/cacoa#52]
`cao$plotSampleDistances(space='expression.shifts', font.size=4, show.sample.size=T, method="UMAP", sample.colors=metadata$version)`
![image](https://github.com/kharchenkolab/cacoa/assets/63233675/d85727ba-3999-42bc-b506-ea163eae24e3)

if I do the following code, I get a black and white image:
`cao$plotSampleDistances(space='expression.shifts', font.size=4, show.sample.size=T, method="UMAP", sample.colors=metadata$sequencing ,palette =  rainbow(3))`
![image](https://github.com/kharchenkolab/cacoa/assets/63233675/dab0569c-fed7-4de6-8b18-4616dc3ddf3b)

**Comment by rrydbirk** [comment]
Hi @Laura19993 

If I remember correctly, you need a named palette, i.e., the names should be "treated_2_", "treated_3_", etc.

/Rasmus

**Comment by Laura19993** [comment]
I tried your suggestion. It does not work. I also tried to give it a named palette with the 3 levels of metadata$sequencing (batch1, batch2, batch3), since I want to colour by sequencing batch, but it also does not work

**Comment by rrydbirk** [comment]
Hi Laura

I just checked, it's `sample.colors` that needs to be named. You can use `sample.groups` for this, so try with

`cao$plotSampleDistances(sample.colors = setNames(metadata$sequencing, names(cao$sample.groups)), palette = rainbow(3))`

Please let me know if you still have problems.

**Comment by Laura19993** [comment]
Hi Rasmus,

sorry for the late reply. It works now. Thank you :)

**Comment by rrydbirk** [comment]
Glad to hear it :-)
