### ISSUE TITLE
What exactly is being plotted with plotCellLoadings?

### ISSUE THREAD

**Issue by milddaa** [kharchenkolab/cacoa#54]
Hello! Thank you for developing Cacoa. I was wondering, what exactly is being plotted with the boxplots in cao$plotCellLoadings()? I extracted the loading values by running cao$test.results$coda$loadings, but neither the mean nor the median of these is what is being plotted with plotCellLoadings. Am I right to assume that you are somehow normalizing the loading values with ref.load.level? Is it simply being subtracted from each loading value? Thank you very much in advance!

**Comment by rrydbirk** [comment]
Hi @milddaa 

Thank you for your interest in our package.

Indeed, it's normalized.

https://github.com/kharchenkolab/cacoa/blob/32e1ad6c596af56772eb27e29d7fcc4a08b89220/R/plot.R#L1108

where `ref.load.level` is extracted from the results, and

https://github.com/kharchenkolab/cacoa/blob/32e1ad6c596af56772eb27e29d7fcc4a08b89220/R/plot.R#L1128-L1137

Please see [plot.R](https://github.com/kharchenkolab/cacoa/blob/32e1ad6c596af56772eb27e29d7fcc4a08b89220/R/plot.R) for additional information, or feel free to ask again. For now, I'll close the issue with this comment.

**Comment by milddaa** [comment]
Hi again! I am also wondering, how are the p-values for each cell type calculated in your package? From the explanation in the preprint I understood that you define the empirical p-value as the minimum value of either proportion of positive loading values among all bootstraps done or proportion of negative loading values among all bootstraps done (formula under Methods section). However, in the coda.R line 200, I find what seems a slightly different definition, where there is also multiplication by 2. I do not fully understand this, so I was wondering, what exactly does that p-value expression in the code mean? Thank you!
